---
name: SQL-ReservedWords-DB2
version: 0.1
author:
  - 'Christian Hansen C<ch@ngmedia.com>'
abstract: Reserved SQL words by DB2
license: perl
requires:
  Sub::Exporter: 0
build_requires:
  Test::More: 0
provides:
  SQL::ReservedWords::DB2:
    file: lib/SQL/ReservedWords/DB2.pm
    version: 0.1
generated_by: Module::Build version 0.2611
